name: fiestavn
repository: https://git.cypherstack.com/FiestaBerry/fiestavn

packages:
  - packages/**
  - examples/**
  -
scripts:
  analyze:
    exec: dart analyze .
  format:
    exec: dart format .
  test:
    exec: dart test