name: renfly_editor
description: "RenFly Editor: write, preview, and package Ren'Py visual novels."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  renpy_core:
    path: ../../packages/renpy_core
  renpy_flutter:
    path: ../../packages/renpy_flutter
  renpy_parser:
    path: ../../packages/renpy_parser
  renpy_writer:
    path: ../../packages/renpy_writer
  file_picker: ^11.0.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
